### PR TITLE
Document the /machine/<machine_id>/decider API

### PR DESCRIPTION
**Pull request by meithecatte**

### CODE REVIEW

**Comment by UncombedCoconut** [comment]
I like it. (@tcosmo?)

**Comment by tcosmo** [comment]
Thank you for the work!

Note that this endpoint is a bit underwhelming in the amount of data that it returns (it only returns a cryptic run name) because the meta-info about a decider is hard coded in the frontend code [https://github.com/bbchallenge/bbchallenge/blob/main/src/lib/tm_decider.svelte](https://github.com/bbchallenge/bbchallenge/blob/main/src/lib/tm_decider.svelte).

Hence, I'm not sure how relevant this endpoint is to the wider public?

I'm not opposed to adding the proposed changes but this endpoint feels like not great UX as such.

What do you think?

**Comment by meithecatte** [comment]
Well, it's better than nothing. I'm not interested in doing the work of exposing nicer decider info, but I do agree that it would be a nice to have.

If anything, we should be able to merge this for now so the API as it exists today is documented, right?

**Comment by tcosmo** [comment]
Ok, let's merge then!

**Pull request merged**
