### PR TITLE
Improve tm rendering 2

### PR DESCRIPTION
**Pull request by tcosmo**
The goal of this PR is to improve the current tm visualisation system of bbchallenge
https://github.com/bbchallenge/website-frontend/issues/2

@[modderme123](https://github.com/modderme123) has proposed interesting changes in this PR https://github.com/bbchallenge/website-frontend/pull/1 which triggered a discussion which is now moved this new PR.

The only request that I would have regarding the proposed changed would be to make then be optional via a checkbox "display scrollable view" for instance. Same for the colors, another checkbox "display states with colors" or something better worded.

### CODE REVIEW

**Comment by modderme123** [comment]
Sounds good, I'm aiming get to this by tomorrow

**Comment by tcosmo** [comment]
I very much like the "explore" idea and the current version is nice, well done!

I like the widening of the simulation screen.

A few remarks:

1. You mentioned zooming but I could not figure out how to zoom on the trace. Traditionallyt + and - would be good key mappings for zoom.

2. I've tried to set the initial state to -5 and 57 and it does not seem to bother the simulation much apart from weird bugs at the beginning of the trace. The behavior that I would expect would be completely black screen: no trace.

3. Also I scrolled and then changed state and I managed to get in the weird attached screenshot state where two traces share the scene. This actually seems to happen if you change any parameter while scrolled in a trace.

4. In explore mode I would probably transform the flex-col containing the machine code and "Go .." buttons to flex-row. But this something that I can do and play with when I'll get a chance.

I'll be happy to merge this after 1. 2. and 3. are addressed :)

Great work!

Screenshot from 2022-03-30 22-18-16

**Comment by modderme123** [comment]
1. pinch (on mac) or cmd-key+scroll (or maybe ctrl-key) should zoom
2. Initial state should be a binary string like 00101010
3. Neat bug, will fix

**Comment by tcosmo** [comment]
1. Really cool! I got it working.

2. Ah! Ok, just a point of vocabulary, traditionally "initial state" means the state (among A,B,C,D,E) on which you start the machine. What you have would be called "initial memory tape". Yeah, controlled input are a pain to do in general. I would use the universal convention that "what is not a 0 is a 1". 

Thank you very much for your work, I will test  it a bit more and re-arrange some bits of my code and we should merge,

**Comment by tcosmo** [comment]
I have found another bug when loading machines with > 5 states such as:

https://proof-bbchallenge.netlify.app/mAQEFAAAAAQADAQAGAQEEAAACAQAFAAEDAQEHAAAEAAAAAQADAQACAQEF&s=20000&w=400&ox=0.08&status=halt

There are some @ in the machine code (even when not in explore mode)

**Comment by modderme123** [comment]
Zoom in such that a single row of the tape occupies 2/3 of the vertical space?

**Comment by modderme123** [comment]
I think I would rather leave that for a separate PR. I've avoided setting the scale too small because my computer can't handle zooming out that far on the larger TMs.

**Comment by tcosmo** [comment]
OK cool!

I will merge as soon as I have time to change the layout a bit.

Thank you for the work :)

**Comment by tcosmo** [comment]
@modderme123 I've done a few things:

1. Set default explore mode zoom to 10 so you really dive right into the machine
2. Added `const MAX_SCROLL_Y = 20;` to prevent the user to scroll too much up and get lost
3. Put the "Eplore mode" checkbox visible on the main page without having to click on Simulation parameters
4. Made a few layout changes for explore mode

If you are happy with these changes we merge :)

Thank you again for your nice work and clean code!

**Comment by modderme123** [comment]
Looks good!

**Comment by tcosmo** [comment]
Merged and pushed to production :)

**Pull request merged**
