### PR TITLE
Add titles

### PR DESCRIPTION
**Pull request by dloranc**
This is a PR to improve SEO and UX when someone has many tabs opened.

### CODE REVIEW

**Review by allezxandre — COMMENTED** [review]
Thanks for the PR!

Is there a reason why you used a store to set the title `onMount`? While it makes the title change-able from anywhere through the store, I believe `onMount` is only run on the client so it prevents pre-rendering from knowing the appropriate title at build time.

**Comment by dloranc** [comment]
@allezxandre you're right! I did it that way because I don't have much experience with Svelte. I had a problem with the main page where titles are somehow refreshed because of a new history state.

Thanks for the feedback, I'll remove the store and think more about this edge case with the homepage.

**Comment by allezxandre** [comment]
Don’t sweat it too much, I think it’s fine to do it like this for now as there are not that many pages that are pre-rendered. 

We’ll just keep it in mind if pre-rendering ever gets used by more pages

**Review by allezxandre — APPROVED** [review]
Looks good to me! 

@tcosmo I'll let you merge this if you're fine with it as well

**Comment by tcosmo** [comment]
Looks good! Thank you

**Pull request merged**
